name: ReplyChatBot
main: laith98\ReplyChatBot\ReplyChatBot
api: [3.0.0]
author: Laith98Dev
version: 1.0.0
description: "Simple plugin to reply chat messages."
website: https://github.com/Laith98Dev

commands:
   bot:
      description: "ReplyChatBot Command"
      permission: "replybot.command.use"

permissions:
   bot:
      default: false
      description: "ReplyChatBot Command"
      children:
          replybot.command.use:
              default: op
              description: "Allows player use all commands"
