name: ReplyChatBot
main: laith98\ReplyChatBot\ReplyChatBot
api: [3.0.0]
author: Laith98Dev
version: 1.0.0
description: ReplyChatBot Auto Bot for replyed messages. 
website: https://github.com/Laith98Dev

commands:
   bot:
      description: AutoChatBot Commands
      permission: replybot.use

permissions:
   bot:
      default: false
      description: "ReplyChatBot Command"
      children:
          replybot.use:
              default: op
              description: "Allows player use all commands"
